pool:
  vmImage: 'Ubuntu 16.04'
trigger:
  branches:
    include:
      - master
      - feature/*
      - bug/*

pr:
  branches:
    include:
      - master

steps:

  - checkout: self
    persistCredentials: true

  - task: Gradle@2
    displayName: 'Building and running tests'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'build --info'
    env:
      AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_DEVICE: $(AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_DEVICE)
      AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_CONTRACT: $(AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_CONTRACT)

  - task: Gradle@2
    displayName: 'Publishing maven artifact'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'publish'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    env:
      AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_DEVICE: $(AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_DEVICE)
      AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_CONTRACT: $(AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_CONTRACT)

  - task: Gradle@2
    displayName: 'Building docker image'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      tasks: 'docker --info'
    env:
      AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_DEVICE: $(AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_DEVICE)
      AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_CONTRACT: $(AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_CONTRACT)

  - script: |
      docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    env:
      DOCKER_ID: $(DOCKER_ID)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
    displayName: 'Logging in to docker'

  - task: Gradle@2
    displayName: 'Publishing docker image'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'dockerPush --info'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    env:
      AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_DEVICE: $(AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_DEVICE)
      AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_CONTRACT: $(AZURE_ARTIFACTS_ENV_ACCESS_TOKEN_CONTRACT)